- name: Load NodeJs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load Prometheus Node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

#- name: Load  schema setup
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: mongo_schema_setup